//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.19 at 10:48:08 AM BST
//


package uk.ac.ebi.jmzml.model.mzml;

import uk.ac.ebi.jmzml.model.mzml.params.AcquisitionSettingsCVParam;
import uk.ac.ebi.jmzml.model.mzml.params.AcquisitionSettingsUserParam;
import uk.ac.ebi.jmzml.model.mzml.utilities.ParamGroupUpdater;
import uk.ac.ebi.jmzml.xml.jaxb.adapters.InstrumentConfigurationAdapter;

import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;


/**
 * Description of the acquisition settings of the instrument prior to the start of the run.
 * <p/>
 * <p/>
 * <p>Java class for AcquisitionSettingsType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="AcquisitionSettingsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://psi.hupo.org/schema_revision/mzML_1.0.0}ParamGroupType">
 *       &lt;sequence>
 *         &lt;element name="sourceFileRefList" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}SourceFileRefListType" minOccurs="0"/>
 *         &lt;element name="targetList" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}TargetListType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="instrumentConfigurationRef" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcquisitionSettingsType", propOrder = {
        "sourceFileRefList",
        "targetList"
        })
public class AcquisitionSettings
        extends ParamGroup
        implements Serializable {

    private final static long serialVersionUID = 100L;
    protected SourceFileRefList sourceFileRefList;
    protected TargetList targetList;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "instrumentConfigurationRef", required = true)
    @XmlJavaTypeAdapter(InstrumentConfigurationAdapter.class)
    @XmlSchemaType(name = "IDREF")
    protected InstrumentConfiguration instrumentConfiguration;

    /**
     * Gets the value of the sourceFileRefList property.
     *
     * @return possible object is
     *         {@link SourceFileRefList }
     */
    public SourceFileRefList getSourceFileRefList() {
        return sourceFileRefList;
    }

    /**
     * Sets the value of the sourceFileRefList property.
     *
     * @param value allowed object is
     *              {@link SourceFileRefList }
     */
    public void setSourceFileRefList(SourceFileRefList value) {
        this.sourceFileRefList = value;
    }

    /**
     * Gets the value of the targetList property.
     *
     * @return possible object is
     *         {@link TargetList }
     */
    public TargetList getTargetList() {
        return targetList;
    }

    /**
     * Sets the value of the targetList property.
     *
     * @param value allowed object is
     *              {@link TargetList }
     */
    public void setTargetList(TargetList value) {
        this.targetList = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the instrumentConfiguration property.
     *
     * @return possible object is
     *         {@link String }
     */
    public InstrumentConfiguration getInstrumentConfiguration() {
        return instrumentConfiguration;
    }

    /**
     * Sets the value of the instrumentConfiguration property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInstrumentConfiguration(InstrumentConfiguration value) {
        this.instrumentConfiguration = value;
    }

    private void afterUnmarshal(Unmarshaller unmarshaller, Object parent) {
        try {
            //update our paramGroup list
            ParamGroupUpdater.updateParamGroupSubclasses(this, AcquisitionSettingsCVParam.class, AcquisitionSettingsUserParam.class);
        } catch (InstantiationException e) {
            throw new RuntimeException(this.getClass().getName() + ".afterUnmarshall: " + e.getMessage());
        } catch (IllegalAccessException e) {
            throw new RuntimeException(this.getClass().getName() + ".afterUnmarshall: " + e.getMessage());
        }
    }

}
