//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.22 at 06:16:33 PM GMT 
//


package uk.ac.ebi.jmzml.model.mzml;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import uk.ac.ebi.jmzml.model.mzml.interfaces.MzMLObject;


/**
 * List with the different components used in the mass spectrometer. At least one source, one mass analyzer and one detector need to be specified.
 * 
 * <p>Java class for ComponentListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComponentListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="source" type="{http://psi.hupo.org/ms/mzml}ComponentType" maxOccurs="unbounded"/>
 *         &lt;element name="analyzer" type="{http://psi.hupo.org/ms/mzml}ComponentType" maxOccurs="unbounded"/>
 *         &lt;element name="detector" type="{http://psi.hupo.org/ms/mzml}ComponentType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentListType", propOrder = {
    "components"
})
public class ComponentList
    implements Serializable, MzMLObject
{

    private final static long serialVersionUID = 100L;
    @XmlElementRefs({
        @XmlElementRef(name = "source", namespace = "http://psi.hupo.org/ms/mzml", type = JAXBElement.class),
        @XmlElementRef(name = "detector", namespace = "http://psi.hupo.org/ms/mzml", type = JAXBElement.class),
        @XmlElementRef(name = "analyzer", namespace = "http://psi.hupo.org/ms/mzml", type = JAXBElement.class)
    })
    protected List<JAXBElement<Component>> components;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger count;

    /**
     * Gets the value of the components property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the components property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Component }{@code >}
     * {@link JAXBElement }{@code <}{@link Component }{@code >}
     * {@link JAXBElement }{@code <}{@link Component }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Component>> getComponents() {
        if (components == null) {
            components = new ArrayList<JAXBElement<Component>>();
        }
        return this.components;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

}
