/*
 * Date: 22/7/2008
 * Author: rcote
 * File: uk.ac.ebi.jmzml.model.mzml.CVParam
 *
 * jmzml is Copyright 2008 The European Bioinformatics Institute
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.19 at 10:48:08 AM BST
//


package uk.ac.ebi.jmzml.model.mzml;

import uk.ac.ebi.jmzml.model.mzml.interfaces.MzMLObject;
import uk.ac.ebi.jmzml.xml.jaxb.adapters.CVAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;


/**
 * This element holds additional data or annotation. Only controlled values are allowed here.
 * <p/>
 * <p/>
 * <p>Java class for CVParamType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="CVParamType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="cvRef" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="accession" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="unitAccession" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="unitName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="unitCvRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CVParamType")
public class CVParam
        implements Serializable, MzMLObject {

    private final static long serialVersionUID = 100L;
    @XmlAttribute(name = "cvRef", required = true)
    @XmlJavaTypeAdapter(CVAdapter.class)
    @XmlSchemaType(name = "IDREF")
    protected CV cv;
    @XmlAttribute(required = true)
    protected String accession;
    @XmlAttribute
    protected String value;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected String unitAccession;
    @XmlAttribute
    protected String unitName;
    @XmlAttribute(name = "unitCvRef")
    @XmlJavaTypeAdapter(CVAdapter.class)
    @XmlSchemaType(name = "IDREF")
    protected CV unitCV;
    @XmlTransient
    protected long hid;

    public long getHid() {
        return hid;
    }

    public void setHid(long hid) {
        this.hid = hid;
    }

    /**
     * Added a boolean to indicate whether this CVParam was inferred from
     * a referenceableParamGroupRef. If so, this cvParam should not be marshalled
     * out, as it will already be marshalled out in the referenceableParamGroupRef.
     * Also, caution is to be used when editing!
     */
    @XmlTransient
    private boolean isInferredFromReferenceableParamGroupRef = false;


    /**
     * Gets the value of the cv property.
     *
     * @return possible object is
     *         {@link String }
     */
    public CV getCv() {
        return cv;
    }

    /**
     * Sets the value of the cv property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCv(CV value) {
        this.cv = value;
    }

    /**
     * Gets the value of the accession property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAccession() {
        return accession;
    }

    /**
     * Sets the value of the accession property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccession(String value) {
        this.accession = value;
    }

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the unitAccession property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getUnitAccession() {
        return unitAccession;
    }

    /**
     * Sets the value of the unitAccession property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUnitAccession(String value) {
        this.unitAccession = value;
    }

    /**
     * Gets the value of the unitName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * Sets the value of the unitName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUnitName(String value) {
        this.unitName = value;
    }

    /**
     * Gets the value of the unitCV property.
     *
     * @return possible object is
     *         {@link String }
     */
    public CV getUnitCV() {
        return unitCV;
    }

    /**
     * Sets the value of the unitCV property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUnitCV(CV value) {
        this.unitCV = value;
    }

    public String toString() {
        return "CVParam{" +
                "cv=" + cv +
                ", accession='" + accession + '\'' +
                ", value='" + value + '\'' +
                ", name='" + name + '\'' +
                ", unitAccession='" + unitAccession + '\'' +
                ", unitName='" + unitName + '\'' +
                ", unitCV=" + unitCV +
                '}';
    }


    /**
     * This boolean indicates whether this CVParam was inferred from
     * a referenceableParamGroupRef. If so, this cvParam should not be marshalled
     * out, as it will already be marshalled out in the referenceableParamGroupRef.
     * Also, caution is to be used when editing the CVParam!
     *
     * @return boolean that indicates whether this CVParam was inferred from
     *                  a referenceableParamGroupRef.
     */
    public boolean isInferredFromReferenceableParamGroupRef() {
        return isInferredFromReferenceableParamGroupRef;
    }

    /**
     * You can set this boolean to indicate whether this CVParam was inferred from
     * a referenceableParamGroupRef. If so, this cvParam will not be marshalled
     * out, as it will already be marshalled out in the referenceableParamGroupRef.
     * Also, caution is to be used when editing the CVParam!
     *
     * @param   inferredFromReferenceableParamGroupRef boolean to indicates whether
     *                                                 this CVParam was inferred from
     *                                                 a referenceableParamGroupRef.
     */
    public void setInferredFromReferenceableParamGroupRef(boolean inferredFromReferenceableParamGroupRef) {
        isInferredFromReferenceableParamGroupRef = inferredFromReferenceableParamGroupRef;
    }
}
