/*
 * Date: 22/7/2008
 * Author: rcote
 * File: uk.ac.ebi.jmzml.model.mzml.Acquisition
 *
 * jmzml is Copyright 2008 The European Bioinformatics Institute
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.19 at 10:48:08 AM BST
//


package uk.ac.ebi.jmzml.model.mzml;

import uk.ac.ebi.jmzml.model.mzml.params.AcquisitionCVParam;
import uk.ac.ebi.jmzml.model.mzml.params.AcquisitionUserParam;
import uk.ac.ebi.jmzml.model.mzml.utilities.ParamGroupUpdater;
import uk.ac.ebi.jmzml.xml.jaxb.adapters.SourceFileAdapter;
import uk.ac.ebi.jmzml.xml.jaxb.adapters.SpectrumAdapter;

import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;


/**
 * Scan or acquisition from original raw file used to create this peak list, as specified in
 * sourceFile.
 * <p/>
 * <p/>
 * <p>Java class for AcquisitionType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="AcquisitionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://psi.hupo.org/schema_revision/mzML_1.0.0}ParamGroupType">
 *       &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="spectrumRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="sourceFileRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="externalNativeID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="externalSpectrumID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcquisitionType")
public class Acquisition
        extends ParamGroup
        implements Serializable {

    private final static long serialVersionUID = 100L;
    @XmlAttribute(required = true)
    protected int number;
    @XmlAttribute(name = "spectrumRef")
    @XmlJavaTypeAdapter(SpectrumAdapter.class)
    @XmlSchemaType(name = "IDREF")
    protected Spectrum spectrum;
    @XmlAttribute(name = "sourceFileRef")
    @XmlJavaTypeAdapter(SourceFileAdapter.class)
    @XmlSchemaType(name = "IDREF")
    protected SourceFile sourceFile;
    @XmlAttribute
    protected String externalNativeID;
    @XmlAttribute
    protected String externalSpectrumID;

    /**
     * Gets the value of the number property.
     */
    public int getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     */
    public void setNumber(int value) {
        this.number = value;
    }

    /**
     * Gets the value of the spectrum property.
     *
     * @return possible object is
     *         {@link String }
     */
    public Spectrum getSpectrum() {
        return spectrum;
    }

    /**
     * Sets the value of the spectrum property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSpectrum(Spectrum value) {
        this.spectrum = value;
    }

    /**
     * Gets the value of the sourceFile property.
     *
     * @return possible object is
     *         {@link String }
     */
    public SourceFile getSourceFile() {
        return sourceFile;
    }

    /**
     * Sets the value of the sourceFile property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSourceFile(SourceFile value) {
        this.sourceFile = value;
    }

    /**
     * Gets the value of the externalNativeID property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getExternalNativeID() {
        return externalNativeID;
    }

    /**
     * Sets the value of the externalNativeID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExternalNativeID(String value) {
        this.externalNativeID = value;
    }

    /**
     * Gets the value of the externalSpectrumID property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getExternalSpectrumID() {
        return externalSpectrumID;
    }

    /**
     * Sets the value of the externalSpectrumID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExternalSpectrumID(String value) {
        this.externalSpectrumID = value;
    }

    private void afterUnmarshal(Unmarshaller unmarshaller, Object parent) {
        try {
            //update our paramGroup list
            ParamGroupUpdater.updateParamGroupSubclasses(this, AcquisitionCVParam.class, AcquisitionUserParam.class);
        } catch (InstantiationException e) {
            throw new RuntimeException(this.getClass().getName() + ".afterUnmarshall: " + e.getMessage());
        } catch (IllegalAccessException e) {
            throw new RuntimeException(this.getClass().getName() + ".afterUnmarshall: " + e.getMessage());
        }
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Acquisition)) return false;

        Acquisition that = (Acquisition) o;

        if (number != that.number) return false;
        if (externalNativeID != null ? !externalNativeID.equals(that.externalNativeID) : that.externalNativeID != null)
            return false;
        if (externalSpectrumID != null ? !externalSpectrumID.equals(that.externalSpectrumID) : that.externalSpectrumID != null)
            return false;
        if (sourceFile != null ? !sourceFile.equals(that.sourceFile) : that.sourceFile != null) return false;
        if (spectrum != null ? !spectrum.equals(that.spectrum) : that.spectrum != null) return false;

        return true;
    }

}
