/*
 * Date: 22/7/2008
 * Author: rcote
 * File: uk.ac.ebi.jmzml.model.mzml.ParamGroup
 *
 * jmzml is Copyright 2008 The European Bioinformatics Institute
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.19 at 10:48:08 AM BST
//


package uk.ac.ebi.jmzml.model.mzml;

import uk.ac.ebi.jmzml.model.mzml.interfaces.MzMLObject;

import javax.xml.bind.annotation.*;
import javax.xml.bind.Marshaller;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;


/**
 * Structure allowing the use of a controlled (cvParam) or uncontrolled vocabulary
 * (userParam), or a reference to a predefined set of these in this mzML file (paramGroupRef).
 * <p/>
 * <p/>
 * <p>Java class for ParamGroupType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ParamGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="referenceableParamGroupRef" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}ReferenceableParamGroupRefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cvParam" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}CVParamType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="userParam" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}UserParamType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParamGroupType", propOrder = {
        "referenceableParamGroupRef",
        "cvParam",
        "userParam"
        })
@XmlSeeAlso({
        SourceFile.class,
        AcquisitionList.class,
        BinaryDataArray.class,
        ProcessingMethod.class,
        Acquisition.class,
        AcquisitionSettings.class,
        Run.class,
        Sample.class,
        InstrumentConfiguration.class,
        Component.class,
        InstrumentConfiguration.class,
        Spectrum.class,
        ProcessingMethod.class,
        Chromatogram.class,
        Scan.class,
        SpectrumDescription.class,
        Scan.class
        })
public class ParamGroup implements Serializable, MzMLObject {

    private static final Logger logger = Logger.getLogger(ParamGroup.class);

    private final static long serialVersionUID = 100L;
    protected List<ReferenceableParamGroupRef> referenceableParamGroupRef;
    protected List<CVParam> cvParam;
    protected List<UserParam> userParam;

    @XmlTransient
    private List<CVParam> cvParamsSkippedDuringMarshalling = new ArrayList<CVParam>();
    @XmlTransient
    private List<UserParam> userParamsSkippedDuringMarshalling = new ArrayList<UserParam>();

    /**
     * Gets the value of the referenceableParamGroupRef property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenceableParamGroupRef property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenceableParamGroupRef().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceableParamGroupRef }
     */
    public List<ReferenceableParamGroupRef> getReferenceableParamGroupRef() {
        if (referenceableParamGroupRef == null) {
            referenceableParamGroupRef = new ArrayList<ReferenceableParamGroupRef>();
        }
        return this.referenceableParamGroupRef;
    }

    /**
     * Gets the value of the cvParam property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cvParam property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCvParam().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link CVParam }
     */
    public List<CVParam> getCvParam() {
        if (cvParam == null) {
            cvParam = new ArrayList<CVParam>();
        }
        return this.cvParam;
    }

    /**
     * Gets the value of the userParam property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userParam property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserParam().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link UserParam }
     */
    public List<UserParam> getUserParam() {
        if (userParam == null) {
            userParam = new ArrayList<UserParam>();
        }
        return this.userParam;
    }

    public boolean beforeMarshalOperation() {
        List<CVParam> cvParams = this.getCvParam();
        List<CVParam> tempCV = new ArrayList<CVParam>();
        for (CVParam cvParam : cvParams) {
            if(cvParam.isInferredFromReferenceableParamGroupRef()) {
                cvParamsSkippedDuringMarshalling.add(cvParam);
                logger.debug("Skipping cvParam " + cvParam);
            } else {
                tempCV.add(cvParam);
            }
        }

        // Replace original list of cvParams with only those that were not inferred
        // (i.e., our temp list).
        this.cvParam = tempCV;

        List<UserParam> userParams = this.getUserParam();
        List<UserParam> tempUser = new ArrayList<UserParam>();
        for (UserParam userParam : userParams) {
            if(userParam.isInferredFromReferenceableParamGroupRef()) {
                userParamsSkippedDuringMarshalling.add(userParam);
                logger.debug("Skipping cvParam " + userParam);
            } else {
                tempUser.add(userParam);
            }
        }

        // Replace original list of cvParams with only those that were not inferred
        // (i.e., our temp list).
        this.userParam = tempUser;

        return true;
    }

    public void afterMarshalOperation() {
        // Reset the thing in its original state.
        cvParam.addAll(cvParamsSkippedDuringMarshalling);
        logger.debug("Re-inserting " + cvParamsSkippedDuringMarshalling.size() + " referenceable CV params into the main cv param list after marshalling.");
        userParam.addAll(userParamsSkippedDuringMarshalling);
        logger.debug("Re-inserting " + userParamsSkippedDuringMarshalling.size() + " referenceable user params into the main user param list after marshalling.");
        // Reset the skipped stuff, as it should now be empty again.
        cvParamsSkippedDuringMarshalling.clear();
        userParamsSkippedDuringMarshalling.clear();
    }

}
