/*
 * Date: 22/7/2008
 * Author: rcote
 * File: uk.ac.ebi.jmzml.model.mzml.MzML
 *
 * jmzml is Copyright 2008 The European Bioinformatics Institute
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.19 at 10:48:08 AM BST
//


package uk.ac.ebi.jmzml.model.mzml;

import uk.ac.ebi.jmzml.model.mzml.interfaces.MzMLObject;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * This is the root element for the Proteomics Standards Initiative (PSI) mzML schema, which
 * is intended to capture the use of a mass spectrometer, the data generated, and the initial processing of
 * that data (to the level of the peak list).
 * <p/>
 * <p/>
 * <p>Java class for mzMLType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="mzMLType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cvList" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}CVListType"/>
 *         &lt;element name="fileDescription" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}FileDescriptionType"/>
 *         &lt;element name="referenceableParamGroupList" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}ReferenceableParamGroupListType" minOccurs="0"/>
 *         &lt;element name="sampleList" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}SampleListType" minOccurs="0"/>
 *         &lt;element name="instrumentConfigurationList" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}InstrumentConfigurationListType"/>
 *         &lt;element name="softwareList" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}SoftwareListType"/>
 *         &lt;element name="dataProcessingList" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}DataProcessingListType"/>
 *         &lt;element name="acquisitionSettingsList" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}AcquisitionSettingsListType" minOccurs="0"/>
 *         &lt;element name="run" type="{http://psi.hupo.org/schema_revision/mzML_1.0.0}RunType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="accession" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mzMLType", propOrder = {
        "cvList",
        "fileDescription",
        "referenceableParamGroupList",
        "sampleList",
        "instrumentConfigurationList",
        "softwareList",
        "dataProcessingList",
        "acquisitionSettingsList",
        "run"
        })
public class MzML
        implements Serializable, MzMLObject {

    private final static long serialVersionUID = 100L;
    @XmlElement(required = true)
    protected CVList cvList;
    @XmlElement(required = true)
    protected FileDescription fileDescription;
    protected ReferenceableParamGroupList referenceableParamGroupList;
    protected SampleList sampleList;
    @XmlElement(required = true)
    protected InstrumentConfigurationList instrumentConfigurationList;
    @XmlElement(required = true)
    protected SoftwareList softwareList;
    @XmlElement(required = true)
    protected DataProcessingList dataProcessingList;
    protected AcquisitionSettingsList acquisitionSettingsList;
    @XmlElement(required = true)
    protected Run run;
    @XmlAttribute
    protected String accession;
    @XmlAttribute(required = true)
    protected String version;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the cvList property.
     *
     * @return possible object is
     *         {@link CVList }
     */
    public CVList getCvList() {
        return cvList;
    }

    /**
     * Sets the value of the cvList property.
     *
     * @param value allowed object is
     *              {@link CVList }
     */
    public void setCvList(CVList value) {
        this.cvList = value;
    }

    /**
     * Gets the value of the fileDescription property.
     *
     * @return possible object is
     *         {@link FileDescription }
     */
    public FileDescription getFileDescription() {
        return fileDescription;
    }

    /**
     * Sets the value of the fileDescription property.
     *
     * @param value allowed object is
     *              {@link FileDescription }
     */
    public void setFileDescription(FileDescription value) {
        this.fileDescription = value;
    }

    /**
     * Gets the value of the referenceableParamGroupList property.
     *
     * @return possible object is
     *         {@link ReferenceableParamGroupList }
     */
    public ReferenceableParamGroupList getReferenceableParamGroupList() {
        return referenceableParamGroupList;
    }

    /**
     * Sets the value of the referenceableParamGroupList property.
     *
     * @param value allowed object is
     *              {@link ReferenceableParamGroupList }
     */
    public void setReferenceableParamGroupList(ReferenceableParamGroupList value) {
        this.referenceableParamGroupList = value;
    }

    /**
     * Gets the value of the sampleList property.
     *
     * @return possible object is
     *         {@link SampleList }
     */
    public SampleList getSampleList() {
        return sampleList;
    }

    /**
     * Sets the value of the sampleList property.
     *
     * @param value allowed object is
     *              {@link SampleList }
     */
    public void setSampleList(SampleList value) {
        this.sampleList = value;
    }

    /**
     * Gets the value of the instrumentConfigurationList property.
     *
     * @return possible object is
     *         {@link InstrumentConfigurationList }
     */
    public InstrumentConfigurationList getInstrumentConfigurationList() {
        return instrumentConfigurationList;
    }

    /**
     * Sets the value of the instrumentConfigurationList property.
     *
     * @param value allowed object is
     *              {@link InstrumentConfigurationList }
     */
    public void setInstrumentConfigurationList(InstrumentConfigurationList value) {
        this.instrumentConfigurationList = value;
    }

    /**
     * Gets the value of the softwareList property.
     *
     * @return possible object is
     *         {@link SoftwareList }
     */
    public SoftwareList getSoftwareList() {
        return softwareList;
    }

    /**
     * Sets the value of the softwareList property.
     *
     * @param value allowed object is
     *              {@link SoftwareList }
     */
    public void setSoftwareList(SoftwareList value) {
        this.softwareList = value;
    }

    /**
     * Gets the value of the dataProcessingList property.
     *
     * @return possible object is
     *         {@link DataProcessingList }
     */
    public DataProcessingList getDataProcessingList() {
        return dataProcessingList;
    }

    /**
     * Sets the value of the dataProcessingList property.
     *
     * @param value allowed object is
     *              {@link DataProcessingList }
     */
    public void setDataProcessingList(DataProcessingList value) {
        this.dataProcessingList = value;
    }

    /**
     * Gets the value of the acquisitionSettingsList property.
     *
     * @return possible object is
     *         {@link AcquisitionSettingsList }
     */
    public AcquisitionSettingsList getAcquisitionSettingsList() {
        return acquisitionSettingsList;
    }

    /**
     * Sets the value of the acquisitionSettingsList property.
     *
     * @param value allowed object is
     *              {@link AcquisitionSettingsList }
     */
    public void setAcquisitionSettingsList(AcquisitionSettingsList value) {
        this.acquisitionSettingsList = value;
    }

    /**
     * Gets the value of the run property.
     *
     * @return possible object is
     *         {@link Run }
     */
    public Run getRun() {
        return run;
    }

    /**
     * Sets the value of the run property.
     *
     * @param value allowed object is
     *              {@link Run }
     */
    public void setRun(Run value) {
        this.run = value;
    }

    /**
     * Gets the value of the accession property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAccession() {
        return accession;
    }

    /**
     * Sets the value of the accession property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccession(String value) {
        this.accession = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

}
