//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.19 at 10:48:08 AM BST
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://psi.hupo.org/schema_revision/mzML_1.0.0",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED,
        attributeFormDefault = javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED
) package uk.ac.ebi.jmzml.model.mzml;
